"""
stage2_neg_hypothesis.py — grouped bad-seed hypothesis feedback, an
alternative to build_context's raw "2 bad seeds" avoid block
(select_failure_examples / n_history_failure), which stays unchanged and
available via its own flag.

Instead of pasting up to 2 individual failed seeds' raw bytes into the
prompt, this finds up to the two largest groups of past bad seeds that
share overlapping edge coverage (i.e. they all failed "the same way"), asks
the LLM to hypothesize — once per group, in its own call — why that whole
group produced no new coverage, and hands those short hypothesis sentences
(not raw seed bytes) to build_context.assemble_prompt via its
history_examples_override hook. Shows fewer than 2 if only one real pattern
has emerged yet (common early in a run, or if a run's bad seeds are
dominated by one recurring mistake), none until at least one qualifies.

Grouping reuses build_context._cluster_failures — the same greedy
edge-Jaccard clusterer that already powers the tight "same mistake"
duplicate detection behind the raw 2-bad-seed feedback — just called with a
much looser threshold (jaccard_min, default 0.3 here vs. HIST_JACCARD_MIN's
0.9) so seeds that broadly share behavior end up in one group instead of
requiring near-identical edge sets.

Cost note (see distill_seed.py's own note on the same tradeoff): this adds
2 extra LLM calls per generation call, once a run's bad-seed pool is large
enough to form 2 qualifying groups. Uses the SAME caller (provider/model)
already configured for seed generation — see run_build_context.py.

Logging: this module only builds prompts/hypotheses and hands back
dicts/strings — run_build_context.py's prompt_fn is what actually writes
each hypothesis call's prompt/response/token-usage into <out_dir>/prompts/
+ <out_dir>/responses/ (mirroring the main generation calls' own
call_NN.json / call_NN.txt split) and <out_dir>/neg_hypothesis_calls.jsonl
(mirroring calls.jsonl), plus the grouping record itself into
<out_dir>/_history/neg_hypotheses.jsonl via append_neg_hypothesis_log.
"""

from __future__ import annotations

import time
from pathlib import Path

import build_context as bc

_NEG_HYPOTHESIS_SYSTEM_TEMPLATE = (
    "You analyze failed fuzzing seeds for AFL++ fuzzing of a {fmt} parser. "
    "You'll be shown several {fmt} inputs previously generated by AI that were all tried and produced "
    "no new coverage. In 1-2 short sentences, give your best guess at what "
    "they share that's preventing new coverage — a structural pattern, a "
    "redundant path, a parsing failure. No preamble, no restating the "
    "seeds, no numbered list."
)


def build_neg_hypothesis_system(fmt: str) -> str:
    """The hypothesis call's system prompt, naming the target format —
    same {fmt} build_context.assemble_prompt's own system prompt names
    (e.g. "XML document") — so the LLM reasons about failures in context,
    not in the abstract."""
    return _NEG_HYPOTHESIS_SYSTEM_TEMPLATE.format(fmt=fmt)

# Default per-seed render budget inside a hypothesis-call prompt (see
# render_group_for_hypothesis's max_chars param — exposed as
# run_build_context.py's --neg-hypothesis-seed-max-chars, not hardcoded
# here, since real AI-generated seeds run up to ~1200 bytes and a too-low
# cap silently hides most of each seed's actual content from the model).
DEFAULT_GROUP_MEMBER_MAX_CHARS = 2000


def _mean_jaccard_to_others(member: dict, members: list) -> float:
    """Mean edge-Jaccard similarity of one cluster member to the rest of its
    cluster — the "how representative is this seed of the group" score."""
    sims = [bc._jaccard(member["edge_ids"], other["edge_ids"])
            for other in members if other is not member]
    return sum(sims) / len(sims) if sims else 0.0


def _most_representative(members: list, k: int) -> list:
    """Keep the k members most representative of the whole cluster (highest
    mean edge-Jaccard to the rest), not the most recent or the smallest —
    gives the hypothesis call the clearest signal of what the group shares."""
    if len(members) <= k:
        return members
    scored = [(_mean_jaccard_to_others(m, members), m) for m in members]
    scored.sort(key=lambda t: t[0], reverse=True)
    return [m for _, m in scored[:k]]


def _distinctive_view(entries: list) -> list:
    """Copies of entries (same status/cycle_id/path/size) with edge_ids
    replaced by (edge_ids - shared_core) — each entry's own edges minus
    whatever core edges the WHOLE pool already has in common — and edge_sig
    recomputed to match, for clustering purposes only.

    Why: a common boilerplate core (e.g. every seed exercises the same
    parser setup/init code) inflates every pairwise edge-Jaccard uniformly,
    so raw edge sets can look "70% similar" across the whole pool even when
    nothing structurally distinguishes them — single-link clustering then
    chains everything into one giant blob and no second group ever
    emerges. Empirically (a real libical run's 31 "redundant" seeds):
    raw-edge pairwise Jaccard was a smooth 0.48-0.95 (one blob, no natural
    split anywhere); Jaccard on the residual after subtracting the
    322-edge shared core was 0.04-0.85 and split cleanly into two
    substantial clusters. Returns entries unchanged if there are too few
    to have a meaningful core, or if the pool doesn't actually share one.

    Needs >= 3 entries, not just >= 2: with exactly 2, core = A & B is BY
    DEFINITION everything those two share, so the residuals (A - core,
    B - core) are always disjoint even when A and B are near-duplicates —
    the subtraction only reveals real structure once there's a third
    entry the "shared core" has to hold across too."""
    if len(entries) < 3:
        return entries
    core = None
    for e in entries:
        core = set(e["edge_ids"]) if core is None else core & e["edge_ids"]
    if not core:
        return entries
    out = []
    for e in entries:
        residual = e["edge_ids"] - core
        e2 = dict(e)
        e2["edge_ids"] = residual
        e2["edge_sig"] = ",".join(map(str, sorted(residual))) if residual else ""
        out.append(e2)
    return out


def select_negative_groups(
    failures: list,
    max_groups: int = 2,
    max_per_group: int = 5,
    min_group_size: int = 2,
    jaccard_min: float = 0.3,
) -> list:
    """Find up to max_groups largest groupings of past bad seeds (from
    build_context.scan_cycle_history's output) that share overlapping edge
    coverage. Returns [{"members": [...], "label": str}, ...], largest group
    first — fewer than max_groups if that's all that qualify (e.g. a run
    dominated by one big "redundant" cluster with no second real pattern
    yet), [] if none do.

    Clustering happens on each seed's DISTINCTIVE edges, not its raw edge
    set — see _distinctive_view's docstring for why (raw edge sets chain
    everything sharing a common core into one blob).

    NO_COVERAGE seeds (didn't parse far enough to hit any code — empty edge
    sets) can never edge-cluster with each other, and rarely share enough
    raw-byte similarity to fall back into one either (they're usually
    unrelated garbage), so build_context._cluster_failures leaves each as
    its own singleton even when there are many of them. "Produced no
    coverage at all" is itself a real, actionable shared trait (the
    existing _cluster_label/_not_parsing distinction already treats it as
    one), so they're pooled into one candidate group here regardless of
    content similarity, instead of being lost as unqualifying singletons.

    Returns [] if no cluster meets min_group_size — this is the "not enough
    of a pool yet" fallback for early calls in a run; it resolves on its
    own as the run's own bad-seed pool grows, no separate
    minimum-pool-size knob needed."""
    if not failures:
        return []

    no_cov = [f for f in failures if f["status"] == "NO_COVERAGE"]
    has_cov = [f for f in failures if f["status"] != "NO_COVERAGE"]

    clusters = bc._cluster_failures(_distinctive_view(has_cov), jaccard_min=jaccard_min)
    clusters = [c for c in clusters if len(c["members"]) >= min_group_size]

    if len(no_cov) >= min_group_size:
        clusters.append({"members": no_cov, "by": "content"})

    if not clusters:
        return []

    clusters.sort(
        key=lambda c: (len(c["members"]), max((m["cycle_id"] or 0) for m in c["members"])),
        reverse=True,
    )

    groups = []
    for c in clusters[:max_groups]:
        members = _most_representative(c["members"], max_per_group)
        label = bc._cluster_label({"members": members, "by": c["by"]})
        groups.append({"members": members, "label": label})
    return groups


def render_group_for_hypothesis(
    members: list, seed_kind: str, max_chars: int = DEFAULT_GROUP_MEMBER_MAX_CHARS
) -> str:
    """Render a group's members into one prompt body for the hypothesis
    call — each labeled by cycle, truncated per-seed at max_chars (a safety
    ceiling for a pathologically huge seed, not a real limit for normal
    AI-generated ones — see DEFAULT_GROUP_MEMBER_MAX_CHARS)."""
    parts = []
    for i, m in enumerate(members, 1):
        try:
            body = bc.format_seed_for_prompt(
                m["path"].read_bytes(), seed_kind, max_chars=max_chars
            )
        except OSError:
            continue
        parts.append(f"--- seed {i} (cycle {m['cycle_id']}) ---\n{body}")
    return "\n\n".join(parts)


def request_group_hypothesis(
    members: list, seed_kind: str, fmt: str, caller,
    max_chars: int = DEFAULT_GROUP_MEMBER_MAX_CHARS,
) -> dict:
    """One extra LLM call: a group's rendered seeds in, a hypothesis for why
    the whole group failed to find new coverage out. fmt is the same
    human-readable target format name build_context.py's own system prompt
    uses (e.g. "XML document" — see run_build_context.py's --fmt), so the
    hypothesis call knows what it's looking at. caller is the same
    batch_harness.ProviderCaller (or any (system, user) ->
    object-with-.text callable) already built for the run's own generation
    calls — see run_build_context.py's `caller`. max_chars is the per-seed
    render budget passed through to render_group_for_hypothesis.

    Returns {"text", "model", "input_tokens", "output_tokens",
    "finish_reason", "attempt_count", "latency_s"} — the hypothesis plus
    whatever call metadata the caller's result exposes (missing fields are
    None), so run_build_context.py can log token/latency usage for these
    calls the same way it already does for the main generation calls."""
    user = render_group_for_hypothesis(members, seed_kind, max_chars=max_chars)
    empty = {"text": "", "model": None, "input_tokens": None, "output_tokens": None,
             "finish_reason": None, "attempt_count": None, "latency_s": None}
    if not user:
        return empty
    t0 = time.monotonic()
    res = caller(build_neg_hypothesis_system(fmt), user)
    latency_s = round(time.monotonic() - t0, 2)
    return {
        "text": res.text.strip(),
        "model": getattr(res, "model", None),
        "input_tokens": getattr(res, "input_tokens", None),
        "output_tokens": getattr(res, "output_tokens", None),
        "finish_reason": getattr(res, "finish_reason", None),
        "attempt_count": getattr(res, "attempt_count", None),
        "latency_s": latency_s,
    }


def append_neg_hypothesis_log(history_dir: Path, call_index: int, groups_with_hypotheses: list) -> None:
    """Append one JSON line to <history_dir>/neg_hypotheses.jsonl, one
    record per call, mirroring batch_harness.append_history_cycle's
    logging convention — so every hypothesis call a run made is auditable
    after the fact. groups_with_hypotheses: [(group, hypothesis_text), ...]."""
    import json

    record = {
        "record_type": "neg_hypothesis_call",
        "call": call_index,
        "groups": [
            {
                "label": group["label"],
                "hypothesis": hyp,
                "n_members": len(group["members"]),
                "cycle_ids": sorted({m["cycle_id"] for m in group["members"] if m["cycle_id"] is not None}),
                "edge_sig_sample": [m["edge_sig"] for m in group["members"]],
            }
            for group, hyp in groups_with_hypotheses
        ],
    }
    with (Path(history_dir) / "neg_hypotheses.jsonl").open("a") as f:
        f.write(json.dumps(record) + "\n")
